version: "3" #버전
services: #이곳에서 쓰이는 service
  redis-server: #컨테이너 이름
    image: "redis" #컨테이너에서 사용하는 이미지
  node-app: #컨테이너 이름
    build: . #현디렉토리에 있는 DockerFile 사용
    ports: # 포트 매핑 로컬포트:컨테이너 포트
      - "5000:8080"
